ACCEPT_TYPES = {
    "application/json": "JSON",
    "text/html": "html",
    "application/html": "html",
    "text/html-partial": "html",
    "text/html-fragment": "html",
    "text/rich": "rtf",
    "application/rtf": "rtf",
    "text/rtf": "rtf",
    "text/plain": "text",
    "application/text": "text",
    "application/markdown": "markdown",
    "text/markdown": "markdown",
    "text/x-markdown": "markdown",
    "image/png": "png",
    "application/pdf": "pdf",
    "json": "JSON",
    "html": "html",
    "rtf": "rtf",
    "plain": "text",
    "text": "text",
    "markdown": "markdown",
    "md": "markdown",
    "png": "png",
    "pdf": "pdf",
}
